#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

valid_branch_regex='^(bug|chore|feat)\([a-zA-Z0-9\-]+(/[a-zA-Z0-9\-]+)?\):\s+[a-zA-Z0-9\-]+)$'

while read line; do
    # Skip comments
    if [ "${line:0:1}" == "#" ]; then
        continue
    fi
    if [ ${#line} -ge 72 ] || [ ${#line} -le 10 ]; then
        echo -e "\033[0;31mThe length of the message has to be between 10 and 72 characters."
        exit 1
    fi
    if [[ "${line}" =~ $valid_branch_regex ]]; then
        echo -e "\033[0;31mCheck your commit message."
    exit 1
fi
done < "${1}"

exit 0
