name: Testing on push

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: pnpm install --no-frozen-lockfile

      - name: Testing
        run: pnpm run test
        env:
          SECRET: ${( secrets.SECRET)}
